package com.example.sprinthub.churchapp.data.models;

public class Video {

    /**
     * The id autogenerated by Firebase
     */
    private String id;
    private String title;

    /**
     * The location of the video (Youtube, Vimeo, etc)
     */
    private String location;

    /**
     * The stream Id can be used to construct the stream url
     */
    private String streamId;

    public Video() {}

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getStreamId() {
        return streamId;
    }

    public void setStreamId(String streamId) {
        this.streamId = streamId;
    }
}
